# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d7ab9ab51fd725e094f55f7ec3bc0d5ff30df04ee9ff19d83656e187079f13340dbc2156972266f9cf6e5859aeaa4c262707ea6bb015d4cbbe3c65782133e72d

test:
  secret_key_base: 5e20e0292e431e7a9ae3b109a104cf0c9ed91f786a386de46e1b960a3f5f0dcf18e74343d61ffca0888cf766059fd470c72388b5216707839fbc7dc7c748ce9e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
